import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author leeaa
 */

public class BOOKING_1 extends javax.swing.JFrame {
String username;
    /**
     * Creates new form BOOKING
     */
 
 public BOOKING_1(String para)
    {
        username=para;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jRadioButton27.setText("UPPER");

        jRadioButton28.setText("MIDDLE");

        jRadioButton29.setText("LOWER");

        jRadioButton33.setText("UPPER");

        jRadioButton34.setText("MIDDLE");

        jRadioButton35.setText("LOWER");

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("BOOK  A TICKET");

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-" }));
        jComboBox8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jComboBox8MouseMoved(evt);
            }
        });
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });

        jLabel22.setText("TRAIN NO:");

        jLabel1.setText("TRAIN NAME:");

        jLabel3.setText("BERTH TYPE:");

        buttonGroup14.add(jRadioButton1);
        jRadioButton1.setText("LOWER ");

        buttonGroup14.add(jRadioButton2);
        jRadioButton2.setText("MIDDLE ");

        buttonGroup14.add(jRadioButton3);
        jRadioButton3.setText("UPPER");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("PASSENGER NAME:");

        jLabel5.setText("CLASS :");

        jLabel6.setText("GENDER:");

        jLabel8.setText("DATE OF JOURNEY:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1A", "2A", "3A", "FC", "CC", "SL", "2S" }));

        buttonGroup15.add(jRadioButton4);
        jRadioButton4.setText("MALE");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        buttonGroup15.add(jRadioButton5);
        jRadioButton5.setText("FEMALE");

        buttonGroup15.add(jRadioButton6);
        jRadioButton6.setText("OTHER");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018" }));

        jLabel12.setText("Train name");
        jLabel12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel12MouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(109, 109, 109))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(96, 96, 96)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jRadioButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRadioButton3))
                                .addComponent(jTextField1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton6)))))
                .addContainerGap(509, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7))
        );

        jLabel9.setText("BOARDING:");

        jLabel11.setText("ALIGHTING:");

        jComboBox6.setMaximumRowCount(4);
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-" }));
        jComboBox6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jComboBox6MouseMoved(evt);
            }
        });
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jComboBox7.setMaximumRowCount(4);
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-" }));
        jComboBox7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jComboBox7MouseMoved(evt);
            }
        });
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jButton2.setText("BOOK MORE TICKETS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("BOOK THIS TICKET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(106, 106, 106)
                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(121, 121, 121)
                .addComponent(jButton2)
                .addGap(263, 263, 263))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new AFTER_LOGIN(username).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try
        {
     
     Class.forName("com.mysql.jdbc.Driver");
     Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/railway","leeaa","Physics@science5");
     Statement st=con.createStatement();
     String query ="Insert into booking values (?,?,?,?,?,?,?,?,?,?,?)";
     PreparedStatement pst =con.prepareStatement(query);
     //PreparedStatement pst1=con.prepareStatement(query);
     pst.setString(1, username);
     pst.setString(2,(String)jComboBox8.getSelectedItem());
     pst.setString(3,(String)jLabel12.getText());
     pst.setString(4,""+jComboBox3.getSelectedItem()+"-"+(jComboBox4.getSelectedIndex()+1)+"-"+jComboBox5.getSelectedItem());
     pst.setString(5,(String)jComboBox2.getSelectedItem());
    pst.setString(6,(String)jComboBox6.getSelectedItem());
    pst.setString(7,(String)jComboBox7.getSelectedItem());
   
    String berth="";
     if(jRadioButton1.isSelected())
     { berth="L";
     
     }
     else if(jRadioButton2.isSelected())
     { berth="M";
     
     }
     else if(jRadioButton3.isSelected())
     { berth="U";
     }
     String query_a="";
     if (berth=="U")
     {query_a="Select u_berth from available where train_no="+jComboBox8.getSelectedItem();} 
     else if (berth=="L")
     { query_a="Select l_berth from available where train_no="+jComboBox8.getSelectedItem();}  
     else if(berth=="M")
     {query_a="Select m_berth from available where train_no="+jComboBox8.getSelectedItem();}      
     PreparedStatement pst_a=con.prepareStatement(query_a);
        ResultSet rs1= pst_a.executeQuery();
        if(rs1.next())
        {
            int no1 = rs1.getInt(1);
          if (no1<=0)
          {
              JOptionPane.showMessageDialog(null,"this seat type is full  \n");          
          }
          else 
          {
              String query5="Drop trigger if exists trig_d";
     String query6="Drop trigger if exists trig_e";
     String query7="Drop trigger if exists trig_f";
            PreparedStatement pst5=con.prepareStatement(query5);
            PreparedStatement pst6=con.prepareStatement(query6);
            PreparedStatement pst7=con.prepareStatement(query7);
            pst5.execute();
            System.out.println("trigger dropped \n");
            pst6.execute();
            System.out.println("trigger dropped \n");
            pst7.execute();
            System.out.println("trigger dropped \n");
     String query0="create trigger trig_d  after insert on booking for each row update available set l_berth=l_berth-1 where train_no="+jComboBox8.getSelectedItem()+" and new.berth='L'";
     PreparedStatement pst0=con.prepareStatement(query0);
     pst0.execute();
   System.out.println("trigger created \n");          
    String query1="create trigger trig_e\n after \n insert on booking\n for each row\n update available\n set m_berth=m_berth-1\n where train_no="+jComboBox8.getSelectedItem()+" and new.berth='M'\n ";
    PreparedStatement pst1=con.prepareStatement(query1);
    pst1.execute();
             System.out.println("trigger createed \n");
            String query2="create trigger trig_f\n after \n insert on booking\n for each row\n update available\n set u_berth=u_berth-1\n where train_no="+jComboBox8.getSelectedItem()+" and new.berth='U'\n ";
            PreparedStatement pst2=con.prepareStatement(query2);
            pst2.execute();
             System.out.println("trigger created \n");
            
     pst.setString(8,berth);
      String gender="";
     if(jRadioButton4.isSelected())
        gender="M";
     else if(jRadioButton5.isSelected())
        gender="F";
     else if(jRadioButton6.isSelected())
        gender="O";
     pst.setString(9,gender);
      int ticket_no;
      String q1="";
      ticket_no=1325 + (int) (Math.random()*4238);
     pst.setInt(10, ticket_no);
     pst.setString(11,jTextField1.getText());
     pst.execute();
     //pst1.execute();
    JOptionPane.showMessageDialog(null,"Successfully booked a ticket! "+jTextField1.getText());
    query5="Drop trigger if exists trig_d";
    query6="Drop trigger if exists trig_e";
    query7="Drop trigger if exists trig_f";
             pst5=con.prepareStatement(query5);
            pst6=con.prepareStatement(query6);
            pst7=con.prepareStatement(query7);
            pst5.execute();
            System.out.println("trigger dropped \n");
            pst6.execute();
            System.out.println("trigger dropped \n");
            pst7.execute();
            System.out.println("trigger dropped \n");
            
    
          }
        }
     
      }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        new BOOKING_1(username).setVisible(true);
        this.setVisible(false);
       // this.setVisible(false);
      /*  try
        {
     
     Class.forName("com.mysql.jdbc.Driver");
     Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/railway","leeaa","Physics@science5");
     Statement st=con.createStatement();
     String query ="Insert into booking values (?,?,?,?,?,?,?,?,?,?,?)";
     PreparedStatement pst =con.prepareStatement(query);
     //PreparedStatement pst1=con.prepareStatement(query);
     pst.setString(1, username);
     pst.setString(2,(String)jComboBox8.getSelectedItem());
     pst.setString(3,(String)jComboBox1.getSelectedItem());
     pst.setString(4,""+jComboBox3.getSelectedItem()+" "+jComboBox4.getSelectedIndex()+1+" "+jComboBox5.getSelectedItem());
     pst.setString(5,(String)jComboBox2.getSelectedItem());
    pst.setString(6,(String)jComboBox6.getSelectedItem());
    pst.setString(7,(String)jComboBox7.getSelectedItem());
   
    String berth="";
     if(jRadioButton1.isSelected())
     { berth="L";
     
     }
     else if(jRadioButton2.isSelected())
     { berth="M";
     
     }
     else if(jRadioButton3.isSelected())
     { berth="U";
     }
     String query5="Drop trigger if exists trig_d";
     String query6="Drop trigger if exists trig_e";
     String query7="Drop trigger if exists trig_f";
            PreparedStatement pst5=con.prepareStatement(query5);
            PreparedStatement pst6=con.prepareStatement(query6);
            PreparedStatement pst7=con.prepareStatement(query7);
            pst5.execute();
            System.out.println("trigger dropped \n");
            pst6.execute();
            System.out.println("trigger dropped \n");
            pst7.execute();
            System.out.println("trigger dropped \n");
    
     String query0="create trigger trig_d  after insert on booking for each row update available set l_berth=l_berth-1 where train_no="+jComboBox8.getSelectedItem()+" and new.berth='L'";
     PreparedStatement pst0=con.prepareStatement(query0);
     pst0.execute();
   System.out.println("trigger created \n");          
    String query1="create trigger trig_e\n after \n insert on booking\n for each row\n update available\n set m_berth=m_berth-1\n where train_no="+jComboBox8.getSelectedItem()+" and new.berth='M'\n ";
            PreparedStatement pst1=con.prepareStatement(query1);
            pst1.execute();
             System.out.println("trigger createed \n");
            String query2="create trigger trig_f\n after \n insert on booking\n for each row\n update available\n set u_berth=u_berth-1\n where train_no="+jComboBox8.getSelectedItem()+" and new.berth='U'\n ";
            PreparedStatement pst2=con.prepareStatement(query2);
            pst2.execute();
             System.out.println("trigger created \n");
            
     pst.setString(8,berth);
      String gender="";
     if(jRadioButton4.isSelected())
        gender="M";
     else if(jRadioButton5.isSelected())
        gender="F";
     else if(jRadioButton6.isSelected())
        gender="O";
     pst.setString(9,gender);
      int ticket_no;
      String q1="";
      ticket_no=1325 + (int) (Math.random()*4238);
     pst.setInt(10, ticket_no);
     pst.setString(11,jTextField1.getText());
     pst.execute();
     //pst1.execute();
    JOptionPane.showMessageDialog(null,"Successfully booked a ticket! "+jTextField1.getText());
    query5="Drop trigger if exists trig_d";
    query6="Drop trigger if exists trig_e";
    query7="Drop trigger if exists trig_f";
             pst5=con.prepareStatement(query5);
            pst6=con.prepareStatement(query6);
            pst7=con.prepareStatement(query7);
            pst5.execute();
            System.out.println("trigger dropped \n");
            pst6.execute();
            System.out.println("trigger dropped \n");
            pst7.execute();
            System.out.println("trigger dropped \n");
            
    
      }
        catch(Exception e)
        {
            System.out.println(e);
        }*/
        
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox8MouseMoved
        // TODO add your handling code here:
        try{
     Class.forName("com.mysql.jdbc.Driver");
     Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/railway","leeaa","Physics@science5");
     
        String query="Select tr_no from trains";
    
        PreparedStatement pst=con.prepareStatement(query);
        ResultSet rs= pst.executeQuery();
        while(rs.next())
        {
            String no = rs.getString(1);
            jComboBox8.addItem(no);
        }
                }
        
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jComboBox8MouseMoved

    private void jComboBox6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox6MouseMoved
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
     Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/railway","leeaa","Physics@science5");   
String query = "select halt_1, halt_2, halt_3 from routes where route_no in(Select route from trains where tr_no="+jComboBox8.getSelectedItem()+")";     
        PreparedStatement pst=con.prepareStatement(query);
        ResultSet rs= pst.executeQuery();
          while(rs.next())
        {
            String no = rs.getString("halt_1");
            jComboBox6.addItem(no);
            no = rs.getString("halt_2");
            jComboBox6.addItem(no);
          no = rs.getString("halt_3");
            jComboBox6.addItem(no);
        }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
     
    }//GEN-LAST:event_jComboBox6MouseMoved

    private void jComboBox7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox7MouseMoved
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
     Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/railway","leeaa","Physics@science5");
    
        String query = "select halt_1, halt_2, halt_3 from routes where route_no in(Select route from trains where tr_no="+jComboBox8.getSelectedItem()+")";     
        PreparedStatement pst=con.prepareStatement(query);
        ResultSet rs= pst.executeQuery();
          while(rs.next())
        {
            String no = rs.getString("halt_1");
            jComboBox7.addItem(no);
             no = rs.getString("halt_2");
            jComboBox7.addItem(no);
             no = rs.getString("halt_3");
            jComboBox7.addItem(no);
       
        }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jComboBox7MouseMoved

    private void jLabel12MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseMoved
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
     Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/railway","leeaa","Physics@science5");
    
        String query = "Select tr_name from trains where tr_no="+jComboBox8.getSelectedItem();     
        PreparedStatement pst=con.prepareStatement(query);
        ResultSet rs= pst.executeQuery();
          while(rs.next())
        {
            String no = rs.getString(1);
            jLabel12.setText(no);
         
        }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel12MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BOOKING_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BOOKING_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BOOKING_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BOOKING_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //
        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
